# Generated by Django 5.0.2 on 2024-02-29 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="название")),
                ("slug", models.SlugField(unique=True, verbose_name="URL")),
                ("description", models.TextField(blank=True, verbose_name="описание")),
                (
                    "sort_number",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="номер п/п"
                    ),
                ),
            ],
            options={
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
                "db_table": "categories",
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=150, verbose_name="вопрос")),
                (
                    "full_text",
                    models.TextField(blank=True, verbose_name="описание вопроса"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="quiz", verbose_name="изображение"
                    ),
                ),
            ],
            options={
                "verbose_name": "вопрос",
                "verbose_name_plural": "вопросы",
                "db_table": "questions",
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_teacher",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        verbose_name="является ли преподавателем",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "профиль пользователя",
                "verbose_name_plural": "профили пользователей",
                "db_table": "profiles",
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.CharField(max_length=150, verbose_name="ответ")),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="правильный ответ"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quiz_app.question",
                        verbose_name="вопрос",
                    ),
                ),
            ],
            options={
                "verbose_name": "ответ",
                "verbose_name_plural": "ответы",
                "db_table": "answers",
            },
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="название")),
                ("slug", models.SlugField(verbose_name="URL")),
                ("description", models.TextField(blank=True, verbose_name="описание")),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="опубликован"),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="создан"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="изменен"),
                ),
                (
                    "sort_number",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="номер п/п"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="quiz_app.category",
                        verbose_name="категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "викторина",
                "verbose_name_plural": "викторины",
                "db_table": "quiz",
                "unique_together": {("slug", "category")},
            },
        ),
        migrations.AddField(
            model_name="question",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="quiz_app.quiz",
                verbose_name="викторина",
            ),
        ),
    ]
